//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintPortalSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComplaintPortalDBEntities : DbContext
    {
        public ComplaintPortalDBEntities()
            : base("name=ComplaintPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<AccountHolder> AccountHolders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ComplaintHandler> ComplaintHandlers { get; set; }
        public virtual DbSet<Supervisor> Supervisors { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<ExternalAgency> ExternalAgencies { get; set; }
        public virtual DbSet<HandlerAssignment> HandlerAssignments { get; set; }
        public virtual DbSet<SupervisorAssignment> SupervisorAssignments { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<AccountLog> AccountLogs { get; set; }
    
        public virtual ObjectResult<GetCaseNumberByUser_Result> GetCaseNumberByUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCaseNumberByUser_Result>("GetCaseNumberByUser", userIdParameter);
        }
    }
}
