using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.DataAccess;
using DevExpress.DashboardCommon;
using System.Data.Entity;

namespace ComplaintPortalSystem.Dashboard
{
    public partial class ComplaintByStatus : DevExpress.DashboardCommon.Dashboard
    {
        public ComplaintByStatus()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            ComplaintPortalSystem.Models.ComplaintPortalDBEntities dbContext = new ComplaintPortalSystem.Models.ComplaintPortalDBEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Complaints.Load();
            // This line of code is generated by Data Source Configuration Wizard
            dashboardObjectDataSource1.DataSource = dbContext.Complaints.Local.ToBindingList();
        }
    }
}
